version: '3.8'

services:
  parrots-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: parrots-frontend-container
    restart: unless-stopped
